t

diff --git a/.github/actions/terraform/destroy/action.yml b/.github/actions/terraform/destroy/action.yml
--- a/.github/actions/terraform/destroy/action.yml
+++ b/.github/actions/terraform/destroy/action.yml
@@ -6,14 +6,11 @@ inputs:
     required: true
   tfvars-file:
     required: true
-  backend-file:
+  backend-file-path:
     required: true
   auto-apply:
     type: boolean
-    default: true
-  working-directory:
-    required: true
-    default: 'main'
+    default: false
 
 runs:
   using: "composite"
@@ -33,16 +30,25 @@ runs:
           terraform_version: ${{ steps.tf-version.outputs.version }}
         
     # ---------------------------------------------
-    # 4. Terraform Init
+    # 4. Terraform Init - Get env backend
     # ---------------------------------------------
     - name: Terraform Init
       shell: bash
       run: |
-        terraform init \
-          -backend-config="${{ inputs.backend-file }}"
+        set -euo pipefail
+        if [ -z "backend.hcl" ]; then
+          echo "ERROR: backend-file-path is missing!"
+          exit 1
+        fi
+
+        terraform init
 
     # Apply
     - name: Terraform Destroy
       run: terraform destroy -auto-approve -var-file=dev.tfvars
       shell: bash
       #working-directory: ./environments/${{ steps.set-env.outputs.environment }}
+    - name: Terraform Apply
+      shell: bash
+      if: ${{ inputs.auto-apply }}
+      run: terraform apply -auto-approve tfplan
diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -4,11 +4,10 @@ on:
   workflow_dispatch:
     inputs:
       auto-apply:
-        type: choice
-        options: [true, false]
+        type: boolean
         description: 'Automatically apply the planned changes'
         required: true
-        default: 'false'
+        default: false
       environment:
         type: choice
         options: [dev, stage, uat, prod]
@@ -33,10 +32,44 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
          
+      - name: Get environment backend file from secret
+        id: backend
+        run: |
+          set -euo pipefail
+         
+          ORIG_ENV="${{ inputs.environment || 'DEV' }}"
+          ENV=$(echo "$ORIG_ENV" | tr '[:lower:]' '[:upper:]')
+
+          echo "Selected environment: $ENV"
+          echo "Looking for secret: TERRAFORM_BACKEND_$ENV"
+
+          SECRET_VAR="TERRAFORM_BACKEND_$ENV"
+          
+          if [ -z "${!SECRET_VAR:-}" ]; then
+            echo "Error: Secret TERRAFORM_BACKEND_$ENV not found or empty!" >&2
+            exit 1
+          fi
+
+          mkdir -p backend
+          BACKEND_FILE="backend/${ENV,,}.hcl"   # creates backend/dev.hcl, backend/stage.hcl etc.
+          
+          echo "${!SECRET_VAR}" > "$BACKEND_FILE"
+          echo "Backend config written to $BACKEND_FILE"
+
+          echo "path=$BACKEND_FILE" >> "$GITHUB_OUTPUT"
+        env:
+          TERRAFORM_BACKEND_DEV:   ${{ secrets.TERRAFORM_BACKEND_DEV }}
+          TERRAFORM_BACKEND_STAGE: ${{ secrets.TERRAFORM_BACKEND_STAGE }}
+          TERRAFORM_BACKEND_UAT:   ${{ secrets.TERRAFORM_BACKEND_UAT }}
+          TERRAFORM_BACKEND_PROD:  ${{ secrets.TERRAFORM_BACKEND_PROD }}
+
       - name: Terraform Destroy
         uses: ./.github/actions/terraform/destroy
         with:
-          environment: dev
-          tfvars-file: dev.tfvars
-          backend-file: dev.backend.tfvars
-          auto-apply: true
+          environment: ${{ inputs.environment || 'dev' }}
+          tfvars-file: ${{ inputs.environment || 'dev' }}.tfvars
+          backend-file-path: ${{ steps.backend.outputs.path }}
+          auto-apply: ${{ inputs.auto-apply || false }}
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
