t

diff --git a/.github/actions/security/terraform-security-scan/action.yml b/.github/actions/security/terraform-security-scan/action.yml
--- a/.github/actions/security/terraform-security-scan/action.yml
+++ b/.github/actions/security/terraform-security-scan/action.yml
@@ -24,6 +24,11 @@ runs:
       run: |
         set -euo pipefail
         cat ${{ inputs.backend-file-path }}
+        if [ -z ${{ inputs.backend-file-path }} ]; then
+          echo "ERROR: backend file is missing!"
+          echo ${{ inputs.backend-file-path }}
+          exit 1
+        fi
         terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
         terraform providers
 
