t

diff --git a/.github/actions/terraform/deploy/action.yml b/.github/actions/terraform/deploy/action.yml
--- a/.github/actions/terraform/deploy/action.yml
+++ b/.github/actions/terraform/deploy/action.yml
@@ -9,10 +9,20 @@ inputs:
   auto-apply:
     type: boolean
     default: true
+  working-directory:
+    required: false
 
 runs:
   using: "composite"
   steps:
+    - name: Enter working_directory directory
+      run: |
+        set -e
+        [ -d "${{ inputs.working-directory }}" ] || (echo "${{ inputs.working-directory }}/ not found!" && ls -la && exit 1)
+        cd ${{ inputs.working-directory }}
+        echo "Working in: $(pwd)"
+      shell: bash
+
     # ---------------------------------------------
     # 1. Get Terraform Version
     # ---------------------------------------------
@@ -36,18 +46,27 @@ runs:
         terraform_version: ${{ steps.tf-version.outputs.version }}
 
     # ---------------------------------------------
-    # 4. Terraform Deploy
+    # 4. Terraform Init
     # ---------------------------------------------
     - name: Terraform Init
+      shell: bash
       run: |
         terraform init \
           -backend-config="${{ inputs.backend-file }}"
 
+    # ---------------------------------------------
+    # 5. Terraform Validate
+    # --------------------------------------------- 
     - name: Terraform Validate
+      shell: bash
       run: terraform validate
 
+    # ---------------------------------------------
+    # 6. Terraform Plan       
+    # ---------------------------------------------
     - name: Terraform Plan
       id: plan
+      shell: bash
       env:
         TF_VAR_environment: ${{ inputs.environment }}
       run: |
@@ -57,6 +76,9 @@ runs:
           -detailed-exitcode
         echo "plan_exitcode=$?" >> $GITHUB_OUTPUT
 
+    # ---------------------------------------------
+    # 7. Terraform Show Plan
+    # ---------------------------------------------
     - name: Show Plan
       if: steps.plan.outputs.exitcode != '0'
       run: terraform show -no-color tfplan
@@ -67,10 +89,7 @@ runs:
         name: tfplan-${{ inputs.environment }}
         path: tfplan
 
-    - name: Show Plan
-      if: steps.plan.outputs.exitcode != '0'
-      run: terraform show -no-color tfplan
-
     - name: Terraform Apply
+      shell: bash
       if: ${{ inputs.auto-apply && steps.plan.outputs.exitcode == '2' }}
       run: terraform apply -auto-approve tfplan
