secured

diff --git a/.github/workflows/terraform-deploy.yml b/.github/workflows/terraform-deploy.yml
--- a/.github/workflows/terraform-deploy.yml
+++ b/.github/workflows/terraform-deploy.yml
@@ -19,9 +19,9 @@ on:
         default: false
       environment:
         type: choice
-        options: [dev, stage, uat, prod]
+        options: [DEV, STAGE, UAT, PROD]
         required: true
-        default: 'dev'
+        default: 'DEV'
 
 permissions:
   contents: read
@@ -35,16 +35,35 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Set UPPER_ENV variable
+      - name: Get environment backend file from secret
         run: |
-          echo "UPPER_ENV=$(echo '${{ inputs.environment }}' | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
+          set -euo pipefail
+
+          ENV="${ENV:-${{ inputs.environment || 'DEV' }}}"
+          SECRET_NAME="TERRAFORM_BACKEND_${ENV}"
+
+          # Fail fast with a clear message if secret is missing
+          if [ -z "${!SECRET_NAME:-}" ]; then
+            echo "Error: Secret $SECRET_NAME not found!" >&2
+            exit 1
+          fi
+
+          mkdir - backend
+          BACKEND_FILE="backend.hcl"
+          # Write the full backend config from the secret
+          echo "${!SECRET_NAME}" > "$BACKEND_FILE"
+
+          echo "Backend config created: $BACKEND_FILE"
+    
+          # Output the path for the next step
+          echo "path=$BACKEND_FILE" >> "$GITHUB_OUTPUT"
 
       - name: Terraform Check, Plan & Apply
         uses: ./.github/actions/terraform/deploy
         with:
           environment: ${{ inputs.environment }}
           tfvars-file: ${{ inputs.environment }}.tfvars
-          backend-file: ${{ secrets[format('AWS_BACKEND_CONFIG_{0}', env.UPPER_ENV)] }}
+          backend-file-path: ${{ steps.backend.outputs.path }}
           auto-apply: ${{ inputs.auto-apply }}
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
